"use client";
export const column = [
  {
    field: "id",
    title: "ID",
    isSortable: true,
    isResizable: false,
    isVisible: true,
    sorDirection: "asc",
  },
  {
    field: "menuId",
    title: "Menu ID",
    isSortable: true,
    isResizable: false,
    isVisible: false,
    sorDirection: "asc",
  },
  {
    field: "menuName",
    title: "Menu Name",
    isSortable: true,
    isResizable: false,
    isVisible: true,
    sorDirection: "asc",
  },
  {
    field: "pageName",
    title: "Page Name",
    isSortable: true,
    isResizable: false,
    isVisible: true,
    sorDirection: "asc",
  },
  {
    field: "controllerName",
    title: "Controller Name",
    isSortable: true,
    isResizable: false,
    isVisible: true,
    sorDirection: "asc",
  },
  {
    field: "actionName",
    title: "Action Name",
    isSortable: true,
    isResizable: false,
    isVisible: true,
    sorDirection: "asc",
  },
  {
    field: "displayOrder",
    title: "Display Order",
    isSortable: true,
    isResizable: false,
    isVisible: true,
    sorDirection: "asc",
  },
];
