"use client";
export const column = [
  {
    field: "id",
    title: "ID",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "appUserId",
    title: "User ID",
    isSortable: true,
    isVisible: false,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "userName",
    title: "User Name",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "roleName",
    title: "Role Name",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "firstName",
    title: "First Name",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "lastName",
    title: "Last Name",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "email",
    title: "Email",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "phoneNumber",
    title: "Phone Number",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "address1",
    title: "Address",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "countryName",
    title: "Country",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "stateName",
    title: "State",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "cityName",
    title: "City",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "panNumber",
    title: "Pan Number",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "aadharNumber",
    title: "Aadhar Number",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "zipCode",
    title: "Zip Code",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
];
