"use client";
export const column = [
  {
    field: "id",
    title: "ID",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "operatorCommissionId",
    title: "Operator Com ID",
    isSortable: true,
    isVisible: false,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "operatorId",
    title: "Operator ID",
    isSortable: true,
    isVisible: false,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "amountTypeId",
    title: "Amount Type ID",
    isSortable: true,
    isVisible: false,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "commissionAmount",
    title: "Commission Amount",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "operatorName",
    title: "Operator Name",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "operatorCode",
    title: "Operator Code",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "commissionMargin",
    title: "Commission Margin",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
  {
    field: "amountTypeSymbol",
    title: "AmountType Symbol",
    isSortable: true,
    isVisible: true,
    isResizable: false,
    sorDirection: "asc",
  },
];
